export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
